# Generated by Django 5.0 on 2024-06-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_managers_usermanager'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.DeleteModel(
            name='UserManager',
        ),
    ]
